services:
  - type: web
    name: neodose-backend
    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn app:app

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: PYTHON_VERSION
        value: 3.11.9

    autoDeploy: true
